import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import Navbar from '@/components/navbar/navbar.component';
import RetroGrid from '@/components/retro-grid/retro-grid.component';

export const metadata: Metadata = {
  title: 'Blvk Rvbbit | Home',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} dark-theme relative`}>
        <div>
          <div className='fixed pulse top-[4rem] left-2  h-[25.5vh] w-[0.1rem] bottom-25 bg-purple'></div>
        </div>
        <Navbar />

        {children}
        <RetroGrid className='fixed bottom-0' />
      </body>
    </html>
  );
}
